---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages:
      - nginx

- name: create nginx conf folder
  become: true
  file:
    path: /etc/nginx/conf.d
    state: directory
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: copy nginx conf (Archlinux)
  become: true
  template:
    src: static.conf
    dest: /etc/nginx/conf.d/static.conf
  register: nginx_conf
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo
  notify: restart nginx

- name: copy nginx conf (MacOSX)
  template:
    src: static.conf
    dest: /opt/homebrew/etc/nginx/servers/static.conf
  register: nginx_conf
  when: ansible_facts.distribution == 'MacOSX'
  notify: restart nginx

- name: enable nginx (Archlinux)
  become: true
  systemd:
    name: nginx
    enabled: true
    state: started
  when:
    - ansible_facts.distribution == 'Archlinux'
    - nginx_conf.changed
  tags:
    - sudo
