---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_ubuntu: [cargo, rustc]

- name: create cargo conf folder
  file:
    path: ~/.cargo
    state: directory

- name: copy cargo conf
  copy:
    src: config
    dest: ~/.cargo/config
