---
- name: restart shadowsocks (Archlinux)
  become: true
  systemd:
    name: shadowsocks@client
    state: restarted
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: restart shadowsocks (MacOSX)
  command: brew services restart shadowsocks-libev
  when: ansible_facts.distribution == 'MacOSX'
