---
- hosts: localhost
  roles:
    # system
    - { role: hostname, tags: ['hostname'] }
    - { role: timedate, tags: ['timedate'] }
    - { role: locale, tags: ['locale'] }
    - { role: mirrorlist, tags: ['mirrorlist'] }
    - { role: grub, tags: ['grub'] }
    - { role: system, tags: ['system'] }
    - { role: user, tags: ['user'] }
    - { role: keyboard, tags: ['keyboard'] }

    # desktop
    - { role: i3, tags: ['i3'] }
    - { role: xinit, tags: ['xinit'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: osx, tags: ['osx'] }
    - { role: rime, tags: ['rime'] }

    # dev
    - { role: git, tags: ['git'] }
    - { role: vim, tags: ['vim'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: node, tags: ['node'] }
    - { role: python, tags: ['python'] }
    - { role: rust, tags: ['rust'] }
    - { role: yazi, tags: ['yazi'] }
    - { role: docker, tags: ['docker'] }
    - { role: ai, tags: ['ai'] }

    # network
    - { role: ssh, tags: ['ssh'] }
    - { role: proxy, tags: ['proxy', 'clash', 'privoxy', 'proxychains'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: mail, tags: ['mail'] }
    # - { role: shadowsocks, tags: ['shadowsocks'] }
    # - { role: trojan, tags: ['trojan'] }
    # - { role: v2ray, tags: ['v2ray'] }

    # apps
    - { role: app, tags: ['app'] }
    - { role: bin, tags: ['bin'] }
    - { role: debug, tags: ['debug'] }
    - { role: firewall, tags: ['firewall'] }

- hosts: ubuntu
  roles:
    - { role: ssh, tags: ['ssh'] }
