---
- name: install proxychains-ng
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [proxychains-ng]
    packages_macos: [proxychains-ng]

- name: set sysconfdir
  set_fact:
    proxychains_sysconfdir: "{{ '/opt/homebrew/etc' if ansible_distribution == 'MacOSX' else '/etc' }}"
  when: ansible_distribution == 'Archlinux' or ansible_distribution == 'MacOSX'

- name: check that the proxychains conf exists
  stat:
    path: '{{ proxychains_sysconfdir }}/proxychains.conf'
  register: proxychains_stat_result
  when: ansible_distribution == 'Archlinux' or ansible_distribution == 'MacOSX'

- name: update proxychains conf
  become: true
  lineinfile:
    dest: '{{ proxychains_sysconfdir }}/proxychains.conf'
    line: 'socks5 127.0.0.1 1080'
    regexp: '^socks'
  when:
    - proxychains_stat_result.stat is defined
    - proxychains_stat_result.stat.exists
