[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.primary]
background = "#fdf6e3"
foreground = "#586e75"

[font]
size = {{ font_size }}
offset = { x = 0, y = 0 }

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001e"
key = "Key6"
mods = "Control"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[window]
opacity = 0.98
startup_mode = "Maximized"
