#!/bin/bash

path="/sys/class/leds/asus::kbd_backlight"

# max should be 3
max=$(cat ${path}/max_brightness)
previous=$(cat ${path}/brightness)
step=1

function commit {
  if [[ $1 = [0-9]* ]]
  then
    if [[ $1 -gt $max ]]
    then
      next=$max
    elif [[ $1 -lt 0 ]]
    then
      next=0
    else
      next=$1
    fi
    echo $next >> ${path}/brightness
    exit 0
  else
    exit 1
  fi
}

case "$1" in
  up)
    commit $(($previous + $step))
    ;;
  down)
    commit $(($previous - $step))
    ;;
  max)
    commit $max
    ;;
  min)
    commit 1
    ;;
  on)
    $0 max
    ;;
  off)
    commit 0
    ;;
  show)
    echo $previous
    ;;
  enable)
    sudo chgrp wheel ${path}/brightness
    sudo chmod g+w ${path}/brightness
    echo 'enable success'
    ;;
  disable)
    sudo chgrp root ${path}/brightness
    sudo chmod g-w ${path}/brightness
    echo 'unable success'
    ;;
  *)
    commit	$1
esac

exit 0
