---
- name: install shadowsocks-libev
  become: true
  apt:
    name: shadowsocks-libev
    update_cache: true
  when:
    - ansible_facts.distribution == 'Debian'
  tags:
    - online
    - sudo

- name: copy shadowsocks conf
  become: true
  copy:
    src: server.json
    dest: /etc/shadowsocks-libev/config.json
  register: shadowsocks_conf
  when:
    - ansible_facts.distribution == 'Debian'
  tags:
    - sudo

- name: enable shadowsocks
  become: true
  systemd:
    name: shadowsocks-libev.service
    enabled: true
  when:
    - ansible_facts.distribution == 'Debian'
  tags:
    - sudo

- name: reload shadowsocks
  become: true
  systemd:
    name: shadowsocks-libev.service
    state: restarted
  when:
    - ansible_facts.distribution == 'Debian'
    - shadowsocks_conf.changed
  tags:
    - sudo
