---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - python-pip
      - uv
    packages_macos:
      - python
      - uv
    packages_ubuntu:
      - python3-pip
      - python-is-python3
    binaries:
      - check: uv
        urls:
          linux-x64: https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-unknown-linux-gnu.tar.gz
          macos-x64: https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-apple-darwin.tar.gz
          macos-arm64: https://github.com/astral-sh/uv/releases/latest/download/uv-aarch64-apple-darwin.tar.gz
        install: tar -xzf $CACHE_FILE -C ~/.local/bin --strip-components=1

- name: add python env to shell rc
  lineinfile:
    path: "~/.{{ item }}rc"
    line: 'export PYTHONUSERBASE="$HOME/.local"'
    insertafter: '^export (?!PATH)'
    create: true
  loop:
    - zsh
    - bash

- name: create pip conf folder
  file:
    path: ~/.config/pip
    state: directory

- name: copy pip conf
  copy:
    src: pip.conf
    dest: ~/.config/pip/pip.conf

- name: create uv conf folder
  file:
    path: ~/.config/uv
    state: directory

- name: copy uv conf
  copy:
    src: uv.toml
    dest: ~/.config/uv/uv.toml
