---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [python-pip]
    packages_macos: [python]
    packages_ubuntu: [python3, python-is-python3]

- name: create pip conf folder
  file:
    path: ~/.config/pip
    state: directory

- name: copy pip conf
  copy:
    src: pip.conf
    dest: ~/.config/pip/pip.conf
