---
- name: install packages
  become: true
  pacman:
    name: python-pip
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'

- name: install packages
  homebrew:
    name: python
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'

- name: install packages
  become: true
  apt:
    name:
      - python3
      - python-is-python3
  when:
    - no_sudo is not defined
    - offline is not defined
    - ansible_distribution == 'Ubuntu'

- name: create pip conf folder
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - ~/.config/pip

- name: copy pip conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: pip.conf, dest: ~/.config/pip/pip.conf }
