---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages: [ranger]

- name: create conf folder
  file:
    path: ~/.config/ranger/plugins
    state: directory

- name: clone ranger plugins
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: no
  loop:
    - { repo: 'https://github.com/jchook/ranger-zoxide.git', dest: ~/.config/ranger/plugins/zoxide }
  when:
    - offline is not defined

- name: copy ranger conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: rc.conf, dest: ~/.config/ranger/rc.conf }
    - { src: rifle.conf, dest: ~/.config/ranger/rifle.conf }
