---
- name: install packages
  become: true
  pacman:
    name: ranger
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'

- name: install packages
  homebrew:
    name: ranger
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'

- name: install ranger
  become: true
  apt:
    name: ranger
  when:
    - no_sudo is not defined
    - offline is not defined
    - ansible_distribution == 'Ubuntu'

- name: create conf folder
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - ~/.config/ranger/plugins

- name: clone ranger plugins
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: no
  with_items:
    - {
        repo: 'https://github.com/jchook/ranger-zoxide.git',
        dest: ~/.config/ranger/plugins/zoxide,
      }
  when:
    - offline is not defined

- name: copy ranger conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: rc.conf, dest: ~/.config/ranger/rc.conf }
    - { src: rifle.conf, dest: ~/.config/ranger/rifle.conf }
