---
- name: install ranger
  become: true
  pacman:
    name: ranger
  when: ansible_distribution == 'Archlinux'

- name: install ranger
  homebrew:
    name: ranger
  when: ansible_distribution == 'MacOSX'

- name: create conf folder
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - ~/.config/ranger/plugins

- name: clone ranger plugins
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    update: no
  with_items:
    - {
        repo: 'git@github.com:jchook/ranger-zoxide.git',
        dest: ~/.config/ranger/plugins/zoxide,
      }

- name: copy ranger conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: rc.conf, dest: ~/.config/ranger/rc.conf }
