---
- name: install packages and binaries
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - yazi
    packages_macos:
      - yazi
    binaries:
      - url: https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-musl.zip
        check: yazi
        install: >-
          unzip -o ~/.cache/ansible/yazi-x86_64-unknown-linux-musl.zip -d /tmp/yazi
          && install /tmp/yazi/yazi-x86_64-unknown-linux-musl/yazi ~/.local/bin/yazi
          && install /tmp/yazi/yazi-x86_64-unknown-linux-musl/ya ~/.local/bin/ya

- name: create conf folder
  file:
    path: ~/.config/yazi
    state: directory

- name: deploy theme config
  copy:
    src: theme.toml
    dest: ~/.config/yazi/theme.toml

- name: deploy keymap config
  copy:
    src: keymap.toml
    dest: ~/.config/yazi/keymap.toml
