---
- name: install packages and binaries
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - yazi
    packages_macos:
      - yazi
    binaries:
      - check: yazi
        urls:
          linux-x64: https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-musl.zip
          macos-x64: https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-apple-darwin.zip
          macos-arm64: https://github.com/sxyazi/yazi/releases/latest/download/yazi-aarch64-apple-darwin.zip
        install: >-
          unzip -o $CACHE_FILE -d /tmp/yazi
          && install /tmp/yazi/$CACHE_STEM/yazi ~/.local/bin/yazi
          && install /tmp/yazi/$CACHE_STEM/ya ~/.local/bin/ya

- name: create conf folder
  file:
    path: ~/.config/yazi
    state: directory

- name: deploy theme config
  copy:
    src: theme.toml
    dest: ~/.config/yazi/theme.toml

- name: deploy keymap config
  copy:
    src: keymap.toml
    dest: ~/.config/yazi/keymap.toml
