---
- name: copy conf
  become: true
  copy:
    src: 40-max-user-watches.conf
    dest: /etc/sysctl.d/40-max-user-watches.conf
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: create logind.conf.d directory
  become: true
  file:
    path: /etc/systemd/logind.conf.d
    state: directory
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: copy logind.conf
  become: true
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf.d/logind.conf
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo
  notify: restart systemd-logind
