---
- name: homebrew tap
  homebrew_tap:
    name: trojan-gfw/trojan
  when: ansible_facts.distribution == 'MacOSX'
  tags:
    - online

- name: install packages
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - trojan
    packages_macos:
      - trojan

- name: copy trojan conf
  become: true
  copy:
    src: config.json
    dest: /etc/trojan/config.json
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo
  notify: restart trojan

- name: copy trojan conf
  copy:
    src: config.json
    dest: /opt/homebrew/etc/trojan/config.json
  when: ansible_facts.distribution == 'MacOSX'
  notify: restart trojan

- name: enable trojan
  become: true
  systemd:
    name: trojan
    enabled: true
    state: started
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: enable trojan (MacOSX)
  command: brew services start trojan
  when: ansible_facts.distribution == 'MacOSX'
  changed_when: false
