---
- name: homebrew tap
  homebrew_tap:
    name: trojan-gfw/trojan
  when: ansible_distribution == 'MacOSX'

- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [trojan]
    packages_macos: [trojan]

- name: copy trojan conf
  become: true
  copy:
    src: config.json
    dest: /etc/trojan/config.json
  when: ansible_distribution == 'Archlinux'
  notify: restart trojan

- name: copy trojan conf
  copy:
    src: config.json
    dest: /opt/homebrew/etc/trojan/config.json
  when: ansible_distribution == 'MacOSX'
  notify: restart trojan

- name: enable trojan
  become: true
  systemd:
    name: trojan
    enabled: true
    state: started
  when: ansible_distribution == 'Archlinux'

- name: enable trojan (MacOSX)
  command: brew services start trojan
  when: ansible_distribution == 'MacOSX'
  changed_when: false
