---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages:
      - zsh
    packages_archlinux:
      - fd
      - xclip
      - scrot
    packages_macos:
      - fd
    packages_ubuntu:
      - fd-find

- name: clone oh-my-zsh
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: false
  loop:
    - repo: https://github.com/robbyrussell/oh-my-zsh.git
      dest: ~/.oh-my-zsh
  tags:
    - online

- name: clone zsh plugins
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: false
  loop:
    - repo: https://github.com/romkatv/powerlevel10k
      dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    - repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags:
    - online

- name: add oh-my-zsh plugins to shell rc
  lineinfile:
    path: ~/.zshrc
    line: "plugins+=({{ item }})"
    insertbefore: '# BEGIN ANSIBLE MANAGED OH-MY-ZSH'
  loop:
    - colored-man-pages
    - history-substring-search
    - vi-mode
    - zsh-autosuggestions
    - zsh-syntax-highlighting

- name: add ZSH env to zshrc
  lineinfile:
    path: ~/.zshrc
    line: 'export ZSH=~/.oh-my-zsh'
    insertafter: '^export (?!PATH)'
    create: true

- name: add oh-my-zsh config to shell rc
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED OH-MY-ZSH"
    block: |
      ZSH_THEME="dstufft"
      source ~/.oh-my-zsh/oh-my-zsh.sh
    create: true
    insertafter: '^plugins\+\='

- name: change default shell to zsh
  become: true
  user:
    name: '{{ ansible_facts["user_id"] }}'
    shell: /bin/zsh
  tags:
    - sudo
