---
- name: copy firewall pac
  become: true
  copy:
    src: public.xml
    dest: /etc/firewalld/zones/public.xml
  register: firewall_conf
  when:
    - ansible_facts.distribution == 'CentOS'
  tags:
    - sudo

- name: reload firewalld
  become: true
  systemd:
    name: firewalld
    enabled: true
    state: reloaded
  when:
    - ansible_facts.distribution == 'CentOS'
    - firewall_conf.changed
  tags:
    - sudo
