# /etc/privoxy/pac.action

{{alias}}
direct = +forward-override{forward .}
ssh    = +forward-override{forward-socks5t 127.0.0.1:1080 .}
https  = +redirect{s@http://@https://@}

{direct}

{ssh}

# feedly
.feedly.com

# medium
.medium.com

# github
.githubusercontent.com
.github.com

# google
.golang.org
.google.com
.googleapis.com
.googleusercontent.com
.gstatic.com

# slack
.slack.com
.slack-edge.com

# v2ex
.v2ex.com

# wiki
.wikipedia.org

# youtube
.youtube.com

# zeplin
.zeplin.io
