---
- name: add repository from PPA
  become: true
  apt_repository:
    repo: ppa:aos1/diff-so-fancy
  when:
    - no_sudo is not defined
    - offline is not defined
    - ansible_distribution == 'Ubuntu'

- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [git, diff-so-fancy, lazygit, tig, meld]
    packages_macos: [git, diff-so-fancy, lazygit, tig]
    packages_cask: [meld]
    packages_ubuntu: [git, diff-so-fancy, tig]

- name: install lazygit (Ubuntu)
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf /tmp/lazygit.tar.gz -C /tmp
    sudo install /tmp/lazygit /usr/local/bin
  args:
    creates: /usr/local/bin/lazygit
  when:
    - no_sudo is not defined
    - offline is not defined
    - ansible_distribution == 'Ubuntu'

- name: create lazygit conf folder
  file:
    path: "{{ '~/Library/Application Support/lazygit' if ansible_distribution == 'MacOSX' else '~/.config/lazygit' }}"
    state: directory

- name: copy .gitconfig
  vars:
    meld: "{{ '/Applications/Meld.app/Contents/MacOS/Meld' if ansible_distribution == 'MacOSX' else ('meld.exe' if ansible_kernel.find('microsoft-standard-WSL2') != -1 else 'meld') }}"
  template:
    src: .gitconfig
    dest: ~/.gitconfig

- name: copy git config
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: .gitconfig-me, dest: ~/.gitconfig-me }
    - { src: .gitconfig-work, dest: ~/.gitconfig-work }
    - { src: .gitconfig-zenvy, dest: ~/.gitconfig-zenvy }

- name: copy lazygit config
  copy:
    src: lazygit.yml
    dest: "{{ '~/Library/Application Support/lazygit/config.yml' if ansible_distribution == 'MacOSX' else '~/.config/lazygit/config.yml' }}"
