---
- name: install packages
  become: true
  pacman:
    name: ['git', 'tig', 'diff-so-fancy', 'meld', 'openbsd-netcat']
  when: ansible_distribution == 'Archlinux'

- name: install packages
  homebrew:
    name: ['tig', 'diff-so-fancy', 'jesseduffield/lazygit/lazygit']
  when: ansible_distribution == 'MacOSX'

- name: install cask packages
  homebrew_cask:
    name: [fork, meld, sublime-merge]
  when: ansible_distribution == 'MacOSX'

- name: create folder ~/.config
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - ~/.config
    - ~/.config/lazygit
    - ~/Library/Application Support/lazygit

- name: copy .gitconfig
  vars:
    meld: 'meld'
  template:
    src: .gitconfig
    dest: ~/.gitconfig
  when: ansible_distribution == 'Archlinux'

- name: copy .gitconfig
  vars:
    meld: '/Applications/Meld.app/Contents/MacOS/Meld'
  template:
    src: .gitconfig
    dest: ~/.gitconfig
  when: ansible_distribution == 'MacOSX'

- name: copy git config
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: .tigrc, dest: ~/.tigrc }
    - { src: .gitconfig-work, dest: ~/.gitconfig-work }
    - { src: .gitconfig-zenvy, dest: ~/.gitconfig-zenvy }

- name: copy lazygit config
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {
        src: lazygit.yml,
        dest: ~/Library/Application Support/lazygit/config.yml,
      }
  when: ansible_distribution == 'MacOSX'

- name: copy lazygit config
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {
        src: lazygit.yml,
        dest: ~/.config/lazygit/config.yml,
      }
  when: ansible_distribution == 'Archlinux'
