---
- name: install xprofile packages
  become: true
  pacman:
    name:
      - arandr
      - blueberry
      - bluez
      - bluez-utils
      - feh
      - gnome-keyring
      - lightdm-gtk-greeter
      - parcellite
      - ttf-firacode-nerd
      - ttf-jetbrains-mono-nerd
      - udiskie
      - wqy-microhei
      - xdg-utils
      - xf86-input-synaptics
      - xf86-video-intel
      - xorg
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'

- name: enable lightdm
  become: true
  systemd:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - bluetooth
    - lightdm
  when: ansible_distribution == 'Archlinux'

- name: copy xprofile conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: .xprofile, dest: ~/.xprofile }
  when: ansible_distribution == 'Archlinux'

- name: enable autologin
  become: true
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
  with_items:
    - { regexp: '^#?autologin-user=', line: 'autologin-user=diartyz' }
    - { regexp: '^#?autologin-user-timeout=', line: 'autologin-user-timeout=0' }
  when: ansible_distribution == 'Archlinux'

- name: create fontconfig folder
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - ~/.config/fontconfig

- name: copy fonts.conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: fonts.conf, dest: ~/.config/fontconfig/fonts.conf }
