---
- name: add pacman config
  become: true
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustAll
      Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
  register: pacmanConf
  when: ansible_distribution == 'Archlinux'

- name: pacman -Sy
  become: true
  pacman:
    update_cache: yes
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'
    - pacmanConf.changed

- name: install packages
  become: true
  pacman:
    name:
      [
        firefox,
        pulsemixer,
        cmus,
        dfc,
        ncdu,
        htop,
        tree,
        unzip,
        yay,
      ]
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'

- name: install cask packages
  homebrew_cask:
    name:
      [
        alfred,
        firefox,
        macs-fan-control,
        omnidisksweeper,
        prefs-editor,
        visual-studio-code,
      ]
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'

- name: install packages
  homebrew:
    name: [mas, dfc, ncdu, htop, tree]
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'

- name: Install Apps
  community.general.mas:
    id:
      - 993841014 # CopyLess 2
    state: present
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'
