---
- name: add pacman config
  become: true
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustAll
      Server = http://mirrors.163.com/archlinux-cn/$arch
  register: pacmanConf
  when: ansible_distribution == 'Archlinux'

- name: pacman -Sy
  become: true
  pacman:
    update_cache: yes
  when:
    - ansible_distribution == 'Archlinux'
    - pacmanConf.changed

- name: install packages
  become: true
  pacman:
    name: [chromium, hardinfo, pulsemixer, bluez, bluez-utils, cmus, mpv, besttrace, dfc, ncdu, htop, tree, yaourt]
  when: ansible_distribution == 'Archlinux'

- name: install cask packages
  homebrew_cask:
    name: ['google-chrome', 'alfred', 'firefox', 'macs-fan-control', 'omnidisksweeper', 'prefs-editor', 'visual-studio-code']
  when: ansible_distribution == 'MacOSX'

- name: install packages
  homebrew:
    name: [mas, mpv, dfc, ncdu, htop, tree]
  when: ansible_distribution == 'MacOSX'

- name: Install Apps
  community.general.mas:
    id:
      - 993841014 # CopyLess 2
    state: present
  when: ansible_distribution == 'MacOSX'
