---
- name: add pacman config
  become: true
  blockinfile:
    dest: /etc/pacman.conf
    block: |
      [archlinuxcn]
      SigLevel = Optional TrustAll
      Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
  register: pacmanConf
  when: ansible_distribution == 'Archlinux'

- name: pacman -Sy
  become: true
  pacman:
    update_cache: true
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'
    - pacmanConf.changed

- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [firefox, pulsemixer, cmus, dfc, ncdu, htop, tree, unzip, yay]
    packages_cask: [alfred, firefox, macs-fan-control, omnidisksweeper, prefs-editor, visual-studio-code]
    packages_macos: [mas, dfc, ncdu, htop, tree]

- name: install Apps from Mac App Store
  community.general.mas:
    id:
      - 993841014  # CopyLess 2
    state: present
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'
