---
- name: create folder ~/.local/bin
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - ~/.local/bin

- name: copy shell scripts
  copy:
    src: '{{ item }}'
    dest: '~/.local/bin/{{ item }}'
    mode: 0755
  with_items:
    - colordump
    - colorribbon
    - colorribbons
