---
- name: create cache and bin directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - ~/.cache/ansible
    - ~/.local/bin
  tags:
    - prepare

- name: copy shell scripts
  copy:
    src: '{{ item }}'
    dest: '~/.local/bin/{{ item }}'
    mode: '0755'
  loop:
    - colordump
    - colorribbon
    - colorribbons

- name: add ~/.local/bin to PATH
  lineinfile:
    path: "~/.{{ item }}rc"
    line: 'export PATH=$HOME/.local/bin:$PATH'
    insertafter: '^export PATH'
    create: true
  loop:
    - zsh
    - bash
