---
- name: create folder ~/.local/bin
  file:
    path: ~/.local/bin
    state: directory

- name: copy shell scripts
  copy:
    src: '{{ item }}'
    dest: '~/.local/bin/{{ item }}'
    mode: '0755'
  loop:
    - colordump
    - colorribbon
    - colorribbons
