---
- name: install packages (Archlinux)
  become: true
  pacman:
    name: "{{ packages_archlinux | default(packages | default([])) }}"
  when:
    - offline is not defined
    - ansible_distribution == 'Archlinux'

- name: install packages (MacOSX)
  homebrew:
    name: "{{ packages_macos | default(packages | default([])) }}"
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'

- name: install cask packages (MacOSX)
  homebrew_cask:
    name: "{{ packages_cask | default([]) }}"
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'
    - packages_cask is defined
    - packages_cask | length > 0

- name: install packages (Ubuntu)
  become: true
  apt:
    name: "{{ packages_ubuntu | default(packages | default([])) }}"
  when:
    - no_sudo is not defined
    - offline is not defined
    - ansible_distribution == 'Ubuntu'
