---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_ubuntu: [mutt, msmtp]

- name: install packages (macOS homebrew)
  homebrew:
    name: [mutt, msmtp]
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'
    - ansible_distribution_major_version | int > 11

- name: install packages (macOS legacy macports)
  macports:
    name: [mutt, msmtp]
  when:
    - offline is not defined
    - ansible_distribution == 'MacOSX'
    - ansible_distribution_major_version | int <= 11

- name: copy mail config
  copy:
    src: .msmtprc
    dest: ~/.msmtprc
    mode: '0600'
