---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages_ubuntu:
      - mutt
      - msmtp

- name: install packages (macOS homebrew)
  homebrew:
    name:
      - mutt
      - msmtp
  when:
    - ansible_facts.distribution == 'MacOSX'
    - ansible_facts.distribution_major_version | int > 11
  tags:
    - online

- name: install packages (macOS legacy macports)
  macports:
    name:
      - mutt
      - msmtp
  when:
    - ansible_facts.distribution == 'MacOSX'
    - ansible_facts.distribution_major_version | int <= 11
  tags:
    - online

- name: copy mail config
  copy:
    src: .msmtprc
    dest: ~/.msmtprc
    mode: '0600'
