---
- name: homebrew tap
  homebrew_tap:
    name: v2ray/v2ray
  when: ansible_facts.distribution == 'MacOSX'
  tags:
    - online

- name: install packages
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - v2ray
    packages_macos:
      - v2ray-core

- name: copy v2ray conf
  become: true
  copy:
    src: config.json
    dest: /etc/v2ray/config.json
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo
  notify: restart v2ray

- name: copy v2ray conf
  copy:
    src: config.json
    dest: /opt/homebrew/etc/v2ray/config.json
  when: ansible_facts.distribution == 'MacOSX'
  notify: restart v2ray

- name: enable v2ray
  become: true
  systemd:
    name: v2ray
    enabled: true
    state: started
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: enable v2ray (MacOSX)
  command: brew services start v2ray-core
  when: ansible_facts.distribution == 'MacOSX'
  changed_when: false
