---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages:
      - dfc
      - htop
      - jq
      - ncdu
      - tree
    packages_archlinux:
      - firefox
      - pulsemixer
      - yay
    packages_cask:
      - firefox
      - macs-fan-control
      - omnidisksweeper
      - prefs-editor
      - visual-studio-code
    packages_macos:
      - mas
    binaries:
      - check: jq
        urls:
          linux-x64: https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64
          macos-x64: https://github.com/jqlang/jq/releases/latest/download/jq-macos-amd64
          macos-arm64: https://github.com/jqlang/jq/releases/latest/download/jq-macos-arm64
        install: >-
          chmod +x $CACHE_FILE
          && install $CACHE_FILE ~/.local/bin/jq
      - check: aliyunpan
        urls:
          linux-x64: https://github.com/tickstep/aliyunpan/releases/download/v0.4.0/aliyunpan-v0.4.0-linux-amd64.zip
          macos-x64: https://github.com/tickstep/aliyunpan/releases/download/v0.4.0/aliyunpan-v0.4.0-darwin-macos-amd64.zip
          macos-arm64: https://github.com/tickstep/aliyunpan/releases/download/v0.4.0/aliyunpan-v0.4.0-darwin-macos-arm64.zip
        install: >-
          unzip -o $CACHE_FILE -d /tmp/aliyunpan
          && install /tmp/aliyunpan/$CACHE_STEM/aliyunpan ~/.local/bin/aliyunpan
      - check: litestream
        urls:
          linux-x64: https://github.com/benbjohnson/litestream/releases/download/v0.5.16/litestream-0.5.16-linux-x86_64.tar.gz
          macos-x64: https://github.com/benbjohnson/litestream/releases/download/v0.5.16/litestream-0.5.16-darwin-x86_64.tar.gz
          macos-arm64: https://github.com/benbjohnson/litestream/releases/download/v0.5.16/litestream-0.5.16-darwin-arm64.tar.gz
        install: >-
          tar -xzf $CACHE_FILE -C /tmp
          && install /tmp/litestream ~/.local/bin/litestream

- name: install Apps from Mac App Store
  community.general.mas:
    id:
      - 993841014 # CopyLess 2
    state: present
  when:
    - ansible_facts.distribution == 'MacOSX'
  tags:
    - online
