---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [tmux, bc]
    packages_macos: [tmux, reattach-to-user-namespace]
    packages_ubuntu: [tmux]

- name: clone tpm
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: no
  loop:
    - { repo: 'https://github.com/tmux-plugins/tpm', dest: ~/.tmux/plugins/tpm }
  when:
    - offline is not defined

- name: copy tmux conf
  copy:
    src: .tmux.conf
    dest: ~/.tmux.conf
