---
- name: install packages
  become: true
  pacman:
    name: tmux
  when: ansible_distribution == 'Archlinux'

- name: install packages
  homebrew:
    name: ['tmux', 'reattach-to-user-namespace']
  when: ansible_distribution == 'MacOSX'

- name: clone oh-my-zsh
  git:
    depth: 1
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    update: no
  with_items:
    - { repo: 'https://github.com/tmux-plugins/tpm', dest: ~/.tmux/plugins/tpm }

- name: copy tmux conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: .tmux.conf, dest: ~/.tmux.conf }
