---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages:
      - tmux
    packages_archlinux:
      - bc
    packages_macos:
      - reattach-to-user-namespace

- name: add tmux plugin to zshrc
  lineinfile:
    path: ~/.zshrc
    line: plugins+=(tmux)
    create: true
    insertbefore: '# BEGIN ANSIBLE MANAGED OH-MY-ZSH'

- name: clone tpm
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: false
  loop:
    - repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm
  tags:
    - online

- name: copy tmux conf
  copy:
    src: .tmux.conf
    dest: ~/.tmux.conf
