---
- name: clone nvm repo
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: no
  loop:
    - { repo: 'https://github.com/creationix/nvm.git', dest: ~/.nvm }
  when:
    - offline is not defined

- name: install node LTS
  shell: 'source ~/.nvm/nvm.sh && nvm install --lts'
  args:
    executable: /bin/bash
    creates: ~/.nvm/alias/default
  when:
    - offline is not defined

- name: copy node config
  copy:
    src: .prettierrc.yml
    dest: ~/.prettierrc.yml
