---
- name: clone nvm repo
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    update: no
  with_items:
    - { repo: 'https://github.com/creationix/nvm.git', dest: ~/.nvm }

- name: Check if node is installed
  command: which node
  ignore_errors: yes
  register: node_check
  changed_when: false

- name: Execute script if foo.node is not installed
  shell: "source ~/.nvm/nvm.sh && nvm install lts/*"
  args:
    executable: /bin/bash
  when: node_check.failed == true

- name: install node packages
  npm:
    name: '{{ item }}'
    global: yes
    registry: https://registry.npm.taobao.org
  with_items:
    - yarn

- name: copy node config
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: .prettierrc.yml, dest: ~/.prettierrc.yml }
    - { src: .npmrc, dest: ~/.npmrc }
    - { src: .yarnrc.yml, dest: ~/.yarnrc.yml }
