---
- name: install packages
  become: true
  pacman:
    name: alacritty
  when: ansible_distribution == 'Archlinux'

- name: copy conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: .alacritty.yml, dest: ~/.alacritty.yml }
    - { src: .Xresources, dest: ~/.Xresources }
  when: ansible_distribution == 'Archlinux'

- name: homebrew tap
  homebrew_tap:
    name: homebrew/cask-fonts
  when: ansible_distribution == 'MacOSX'

- name: install cask packages
  homebrew_cask:
    name: [iterm2, font-jetbrains-mono-nerd-font, font-fira-code-nerd-font]
  when: ansible_distribution == 'MacOSX'
