---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - alacritty
    packages_cask:
      - alacritty

- name: copy .Xresources
  copy:
    src: .Xresources
    dest: ~/.Xresources
  when: ansible_facts.distribution == 'Archlinux'

- name: copy .alacritty.toml
  vars:
    font_size: "{{ 13 if ansible_facts.distribution == 'MacOSX' else 11 }}"
  template:
    src: .alacritty.toml
    dest: ~/.alacritty.toml

- name: homebrew tap
  homebrew_tap:
    name: homebrew/cask-fonts
  when:
    - ansible_facts.distribution == 'MacOSX'
  tags:
    - online

- name: install cask font packages
  homebrew_cask:
    name:
      - font-jetbrains-mono-nerd-font
      - font-fira-code-nerd-font
  when:
    - ansible_facts.distribution == 'MacOSX'
  tags:
    - online
