---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [shadowsocks]
    packages_macos: [shadowsocks-libev]

- name: copy shadowsocks conf (Archlinux)
  become: true
  copy:
    src: client.json
    dest: /etc/shadowsocks/client.json
  when: ansible_distribution == 'Archlinux'
  notify: restart shadowsocks

- name: copy shadowsocks conf (MacOSX)
  copy:
    src: client.json
    dest: /opt/homebrew/etc/shadowsocks-libev.json
  when: ansible_distribution == 'MacOSX'
  notify: restart shadowsocks

- name: enable shadowsocks
  become: true
  systemd:
    name: shadowsocks@client
    enabled: true
    state: started
  when: ansible_distribution == 'Archlinux'

- name: enable shadowsocks (MacOSX)
  command: brew services start shadowsocks-libev
  when: ansible_distribution == 'MacOSX'
  changed_when: false
