---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages_archlinux:
      - shadowsocks
    packages_macos:
      - shadowsocks-libev

- name: copy shadowsocks conf (Archlinux)
  become: true
  copy:
    src: client.json
    dest: /etc/shadowsocks/client.json
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo
  notify: restart shadowsocks

- name: copy shadowsocks conf (MacOSX)
  copy:
    src: client.json
    dest: /opt/homebrew/etc/shadowsocks-libev.json
  when: ansible_facts.distribution == 'MacOSX'
  notify: restart shadowsocks

- name: enable shadowsocks
  become: true
  systemd:
    name: shadowsocks@client
    enabled: true
    state: started
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: enable shadowsocks (MacOSX)
  command: brew services start shadowsocks-libev
  when: ansible_facts.distribution == 'MacOSX'
  changed_when: false
