---
# - name: show facts available on the system
#   debug:
#     var: ansible_facts

- name: show ansible_facts.distribution
  debug:
    msg: '{{ ansible_facts.distribution }}'

- name: show ansible_facts.distribution_major_version
  debug:
    msg: '{{ ansible_facts.distribution_major_version }}'

- name: show ansible_user_id
  debug:
    msg: '{{ ansible_user_id }}'

- name: show ansible_user_dir
  debug:
    msg: '{{ ansible_user_dir }}'

- name: show ansible_facts.kernel
  debug:
    msg: '{{ ansible_facts.kernel }}'
