---
- name: show ansible_distribution
  debug:
    msg: '{{ ansible_distribution }}'

- name: show major version
  debug:
    msg: '{{ ansible_distribution_major_version }}'

- name: show username
  debug:
    msg: '{{ ansible_user_id }}'

- name: show ansible_user_dir
  debug:
    msg: '{{ ansible_user_dir }}'
