---
- name: copy v2ray conf
  become: true
  copy:
    src: config.json
    dest: /etc/v2ray/config.json
  register: v2ray_conf
  when:
    - ansible_facts.distribution == 'Debian'
  tags:
    - sudo

- name: enable v2ray
  become: true
  systemd:
    name: v2ray
    enabled: true
  when:
    - ansible_facts.distribution == 'Debian'
  tags:
    - sudo

- name: reload v2ray
  become: true
  systemd:
    name: v2ray
    state: restarted
  when:
    - ansible_facts.distribution == 'Debian'
    - v2ray_conf.changed
  tags:
    - sudo
