---
- name: install packages
  include_role:
    name: install-packages
  vars:
    packages_archlinux: [docker, docker-machine]
    packages_cask: [docker]

- name: create conf folder
  become: true
  file:
    path: /etc/docker
    state: directory
  when: ansible_distribution == 'Archlinux'

- name: copy docker conf
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  when: ansible_distribution == 'Archlinux'
