---
- name: install packages
  become: true
  pacman:
    name: ibus-rime
  register: rime
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - online
    - sudo

- name: set confdir
  set_fact:
    confdir: "{{ '~/Library/Rime' if ansible_facts.distribution == 'MacOSX' else '~/.config/ibus/rime' }}"
  when: ansible_facts.distribution == 'Archlinux' or ansible_facts.distribution == 'MacOSX'

- name: create conf folder
  file:
    path: '{{ confdir }}'
    state: directory
  when: ansible_facts.distribution == 'Archlinux' or ansible_facts.distribution == 'MacOSX'

- name: clone rime-ice repo
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    depth: 1
    update: false
  loop:
    - repo: https://github.com/rime/plum
      dest: '{{ confdir }}/plum'
  register: rime_clone
  when:
    - ansible_facts.distribution == 'Archlinux' or ansible_facts.distribution == 'MacOSX'
  tags:
    - online

- name: execute rime-install script
  shell: bash rime-install iDvel/rime-ice:others/recipes/full
  args:
    executable: /bin/bash
    chdir: '{{ confdir }}/plum'
  when:
    - rime_clone.changed
  tags:
    - online

- name: copy conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - src: default.custom.yaml
      dest: '{{ confdir }}/default.custom.yaml'
    - src: luna_pinyin_simp.custom.yaml
      dest: '{{ confdir }}/luna_pinyin_simp.custom.yaml'
    - src: rime_ice.custom.yaml
      dest: '{{ confdir }}/rime_ice.custom.yaml'
  when: ansible_facts.distribution == 'Archlinux' or ansible_facts.distribution == 'MacOSX'
