---
- name: restart trojan (Archlinux)
  become: true
  systemd:
    name: trojan
    state: restarted
  when:
    - ansible_facts.distribution == 'Archlinux'
  tags:
    - sudo

- name: restart trojan (MacOSX)
  command: brew services restart trojan
  when: ansible_facts.distribution == 'MacOSX'
