---
- name: install packages
  include_role:
    name: pkg
  vars:
    packages:
      - neovim
      - ripgrep
    packages_archlinux:
      - gvim
      - python-pynvim
    packages_macos:
      - vim
    packages_ubuntu:
      - vim-gtk3
    binaries:
      - url: https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz
        check: rg
        install: >-
          tar -xzf ~/.cache/ansible/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz -C /tmp
          && install /tmp/ripgrep-15.1.0-x86_64-unknown-linux-musl/rg ~/.local/bin/rg
      - url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
        check: nvim
        install: tar -xzf ~/.cache/ansible/nvim-linux-x86_64.tar.gz -C ~/.local --strip-components=1

- name: install pynvim
  pip:
    name: pynvim
    extra_args: --user
  when: ansible_facts.distribution != 'Archlinux'
  tags:
    - online

- name: add vim alias and env to shell rc
  lineinfile:
    path: "~/.{{ item.0 }}rc"
    line: "{{ item.1.line }}"
    insertafter: "{{ item.1.after }}"
    create: true
  loop: "{{ ['zsh', 'bash'] | product([
    {'line': 'alias vi=\"nvim\"', 'after': '^alias'},
    {'line': 'export EDITOR=vim', 'after': '^export (?!PATH)'},
    {'line': 'export KEYTIMEOUT=1', 'after': '^export (?!PATH)'},
  ]) | list }}"

- name: create vim & nvim conf folder
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - ~/.vim/autoload
    - ~/.local/share/nvim/site/autoload
    - ~/.config/nvim

- name: check vim-plug
  stat:
    path: ~/.vim/autoload/plug.vim
  register: vim_plug

- name: download vim-plug for vim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
  when:
    - not vim_plug.stat.exists
  tags:
    - online

- name: copy vim conf
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - src: .vimrc
      dest: ~/.vimrc
    - src: init.lua
      dest: ~/.config/nvim/init.lua
    - src: lua
      dest: ~/.config/nvim

- name: install win32yank (WSL2)
  become: true
  shell: |
    set -e
    curl -Lo /tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/latest/download/win32yank-x64.zip
    unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
    chmod +x /tmp/win32yank.exe
    mv /tmp/win32yank.exe /usr/local/bin/
  args:
    creates: /usr/local/bin/win32yank.exe
  when:
    - ansible_facts.kernel.find('microsoft-standard-WSL2') != -1
  tags:
    - online
    - sudo
