# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
notARepository: skip
git:
  pagers:
    - pager: delta --paging=never
  commit:
    signOff: true
gui:
  theme:
    selectedLineBgColor:
      - reverse
